# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-16 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=200)),
                ('style', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=200)),
                ('style', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=200)),
                ('style', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teleplay',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=200)),
                ('style', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videodetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staus', models.CharField(blank=True, max_length=500, null=True)),
                ('protagonist', models.CharField(blank=True, max_length=500, null=True)),
                ('correlation', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('director', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=500, null=True)),
                ('language', models.CharField(blank=True, max_length=500, null=True)),
                ('synopsis', models.CharField(blank=True, max_length=500, null=True)),
                ('cartoon', models.ForeignKey(blank=True, db_column='cid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vdetail', to='App.Cartoon')),
                ('film', models.ForeignKey(blank=True, db_column='fid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vdetail', to='App.Film')),
                ('shows', models.ForeignKey(blank=True, db_column='sid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vdetail', to='App.Shows')),
                ('teleplay', models.ForeignKey(blank=True, db_column='tid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vdetail', to='App.Teleplay')),
            ],
        ),
    ]
